export enum TipoFertilizante {
  NITROGENADO_SIMPLE = 'NITROGENADO_SIMPLE',
  FOSFATADO_SIMPLE = 'FOSFATADO_SIMPLE',
  POTASICO_SIMPLE = 'POTASICO_SIMPLE',
  COMPUESTO = 'COMPUESTO',
  ORGANICO = 'ORGANICO',
  ENMIENDA = 'ENMIENDA',
  MICRONUTRIENTE = 'MICRONUTRIENTE'
}
